# Generated by Django 2.1.2 on 2018-10-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=40)),
                ('senha', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
    ]
